### ISSUE TITLE
This line makes me feel stupid

### ISSUE THREAD

**Issue by brbarnett** [paulhermany/aoc#1]
https://github.com/paulhermany/aoc/blob/6074920feb0a176a8a0b619e588aa96649ba7bf7/Hermany.AoC/Day03/Day03.cs#L31-L32

How on earth does this work?

**Comment by paulhermany** [comment]
We start off from (0,0) facing East or at 0 radians.
After the first step ("walking" East), we are at (1,0).

In order to generate the spiral, the code checks the position to the left (rotated counter-clockwise 90 degrees or Math.PI/2 radians) which is (1,1).  If the position has already been visited, we need to keep walking in the same direction, otherwise, we turn left by adding Math.PI/2 to the direction.

Since you can keep adding Math.PI/2 to the angle forever (or at least until arithmetic overflow) and x and y will increment 1,0,-1,0 forever.
Facing East, Math.Cos(0) = 1 and Math.Sin(0) = 0
Facing North, Math.Cos(Math.PI/2) = 0 and Math.Sin(Math.PI/2) =1
Facing West, Math.Cos(Math.PI) = -1 and Math.Sin(Math.PI) = 0
Facing West, Math.Cos(3*Math.PI/2) = 0 and Math.Sin(3*Math.PI/2) = -1

It avoids having to do a big switch or if-then-else to determine the direction based on some kind of flag or enum.  I believe it's actually LESS efficient to do it this way, but it's less code.
